c
c.....Constants used in the calculation.
c
      parameter  (zero       =   0.0d+00)
      parameter  (one        =   1.0d+00)
      parameter  (two        =   2.0d+00)
      parameter  (hundred    = 100.0d+00)
      parameter  (izero      =     0)
      parameter  (tenp       =  10.0d+00)
      parameter  (twohundred = 200.0d+00)
      parameter  (half       = 0.5d+00)
      parameter  (epsq12     = 1.0d-12)
      parameter  (epsq10     = 1.0d-10)
      parameter  (epsq8      = 1.0d-8)
      parameter  (ncdw       =   500)
      parameter  (xlog2      = 0.69314718055994530941D+00)
c
c.....Constants used in qqsort.f
c
      parameter  (fm         = 7875.0d+00)
      parameter  (fa         =  211.0d+00)
      parameter  (fc         = 1663.0d+00)
      parameter  (fmi        = 1.2698413d-4)
