c
c.....................................................................................
c
      subroutine edfcrit (lr,lw,lu18)
c
c.....................................................................................
c
c                                                                 ooo
c                                                                 ooo
c
c  EEEEEEEEEE DDDDDDDD      FFFFFFFFFFF CCCCCCCCCCC RRRRRRRRRR    III TTTTTTTTTTTTT
c  EEEEEEEEEE DDDDDDDDDD    FFFFFFFFFFF CCCCCCCCCCC RRRRRRRRRRR   III TTTTTTTTTTTTT
c  EEE        DDD    DDDD   FFF         CCC         RRR       RR  III      TTT          
c  EEE        DDD       DDD FFF         CCC         RRR       RRR III      TTT        
c  EEE        DDD       DDD FFF         CCC         RRR       RR  III      TTT        
c  EEEEEEEEE  DDD       DDD FFFFFFFFFF  CCC         RRRRRRRRRRR   III      TTT        
c  EEEEEEEEE  DDD       DDD FFFFFFFFFF  CCC         RRRRRRRRRR    III      TTT        
c  EEE        DDD       DDD FFF         CCC         RRR    RRR    III      TTT           
c  EEE        DDD       DDD FFF         CCC         RRR     RRR   III      TTT           
c  EEE        DDD    DDDD   FFF         CCC         RRR     RRR   III      TTT        
c  EEEEEEEEEE DDDDDDDDDD    FFF         CCCCCCCCCCC RRR      RRR  III      TTT
c  EEEEEEEEEE DDDDDDDD      FFF         CCCCCCCCCCC RRR       RRR III      TTT
c
c.....................................................................................
c
c.....This routine deals with COMPLEX Atomic Overlap Matrices (AOMs) written
c     by the CRITIC2 program. This program writes a binary file containing
c     these AOM integrals, as well as some other data specifying the features
c     of the solid state electronic structure calculation, performed by
c     another program (typically, the QUANTUM EXPRESSO code), that generate
c     those AOM integrals. 
c
c     After reading the first record with the value of IOVERLAP from the
c     (standard unit) input file, and the second one with the name of 
c     the file containing the AOM, this routine is called in case that 
c     IOVERLAP=-2. The data to be read from the binary file with logical
c     unit LU18 is described below.
c
c-----Las Atomic Overlap Matrices (AOM) can be read in directly from the 
c     checkpoint file, with extension "chk-sij", generated by default by
c     the CRITIC2 program during the integration. There are two modes
c     of operating with the code: (1) Wannier functions can be integrated
c     as described in the article (A. Otero de-la-roza et al, J. Chem.
c     Theory and Comput. 14, 4699–4710 (2018)), and (2) Block functions can 
c     also be integrated directly. The integration routines included in the
c     file 'integration@proc.f90' of the source code of CRITIC2 are 
c     labeled as _wannier y _psink for these of modes, respectively.
c
c
c     The file with logical unit LU18 is in this case binary and has the 
c     following records (routine 'write_sijchk' within the 
c     'integration@proc.f90'  file in the source code  of CRITIC2).
c
c
c     +++++++++++++++++++++++++++++++++++++++++++++++++
c     +                                               +
c     +  Structure of the AOM file written by CRITIC2 +
c     +                                               +
c     +++++++++++++++++++++++++++++++++++++++++++++++++
c
c
c=====Record 1: NBND, NBNDW, NLAT, NMO, NLATTOT, NSPIN, NATTR, SIJTYPE
c
c++++ NBND       (integer)  
c
c     Number of bands 
c
c++++ NBNDW(1:2) (integer)   
c
c     For the spin channel i (i=1 or 2) all the bands up to NBNDW(i) 
c     have a significant occupation. This variable is used to determine
c     which bands are unoccupied in the 'wannier' mode and systems with
c     spin-polarization. If the system is no spin-polarized, 
c     NBNDW(:) = NBND.
c
c++++ NLAT(1:3) (integer)
c
c     For the 'wannier' mode, number of vectors of the real lattice. For 
c     the 'psink' mode, number of \vec(k) points in the first Brillouin 
c     (1BZ) zone along each direction of reciprocal space. In both cases, 
c     it is  mandatory that the grid is uniform and that it includes the 
c     origin (i.e. without translation)
c
c++++ NLATTOT (integer)
c
c     Total number of (vectors of the real lattice/points of 1BZ). It
c     must be equal to NLAT(1)*NLAT(2)*NLAT(3).
c
c++++ NMO (integer)
c
c     Number of molecular orbitals (MO). It must be NMO = NLATTOT * NBND.
c
c++++ NSPIN (integer)
c
c     Number of spin-channels. It must be NSPIN=1 or NSPIN=2.
c
c++++ NATTR (integer)
c
c     Number of attractors in the unit cell. If the integration procedure
c     in CRITIC2 uses the default behavior, the nuclear attractors are 
c     listed first, in the same order they appear in the output of
c     CRITIC2 ("List of atoms in the unit cell"), and then the non-muclear
c     attractors (NNM). In any case, the order of attractors is that
c     one appearing in the list "Integrated atomic properties" of the 
c     output file of CRITIC2.
c
c++++ SIJTYPE
c
c     Variable used to interpret the Sij values (1='wannier',2='psink')
c    
c=====Record 2: KPT(1:3,1:NLATTOT) (real*8)
c
c++++ Coordinates of the \vec{k} points in the 1BZ. Fractional units, 
c     reciprocal space. They are only used in the 'psink' mode to compute
c     the phase factor.
c
c
c=====Record 3: OCCRIT(1:NBND,1:NLATTOT,1:NSPIN) (real*8)
c
c++++ Orbital occupations: OCCRIT(i,j,k) is the occupation number of band
c     'i', k-point 'j', and spin 'k'. They are only used in the 'psink'
c     mode. In the 'wannier' mode, CRITIC2 assumes that there are no
c     partially filled bands, so that all occupations are 0, 1, or 2,
c     depending on the spin value and the value of the NBND and NBNDW(1:2)
c     values.
c
c=====Record 4: SIJ(1:NMO,1:NMO,1:NATTR,1:NSPIN) (complex*16)
c
c     SIJ(i,j,k,l) is the overlap matrix between the MOs 'i' and 'j'
c     in the attraction basin 'k' with spin 'l'. 'k' and 'l' are simple
c     indices, but 'i' and 'j' are a packing of the lattice vector 
c     ('wannier') or k-point ('psink') and the band index. To loop through 
c     one of the indices, do:
c
c     do imo = 1, nmo
c       call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
c     enddo
c
c     The 'unpackidx' routine uses the index of the orbital ('imo') 
c     and the dimensions of the problem ('nmo', 'nbnd', 'nlat') 
c     returning the index of the band ('iba') and the indices of the 
c     three vectors of the lattice or k-vector points ('ia','ja','ka').
c     The inverse operation is:
c
c     do idx = 1, nmo
c       call packidx (io,jo,ko,bo,idx,nmo,nbnd,nlat)
c     enddo
c
c     The 'unpackidx' and 'packidx' routines are simple enough as to be
c     given here:
c
c
c     subroutine unpackidx(idx,io,jo,ko,bo,nmo,nbnd,nlat)
c       integer, intent(in) :: idx, nmo, nbnd, nlat(3)
c       integer, intent(out) :: io, jo, ko, bo
c     
c       integer :: iaux
c     
c       ! unpack
c       iaux = modulo(idx-1,nmo)
c       bo = modulo(iaux,nbnd)
c       iaux = (idx-1 - bo) / nbnd
c       ko = modulo(iaux,nlat(3))
c       iaux = (iaux - ko) / nlat(3)
c       jo = modulo(iaux,nlat(2))
c       iaux = (iaux - jo) / nlat(2)
c       io = modulo(iaux,nlat(1))
c       bo = bo + 1
c     
c     end subroutine unpackidx
c
c     subroutine packidx(io,jo,ko,bo,idx,nmo,nbnd,nlat)
c       integer, intent(in) :: io, jo, ko, bo, nmo, nbnd, nlat(3)
c       integer, intent(out) :: idx
c     
c       integer :: zio, zjo, zko
c     
c       ! transformed indices
c       zio = modulo(io,nlat(1))
c       zjo = modulo(jo,nlat(2))
c       zko = modulo(ko,nlat(3))
c     
c       ! translate and pack
c       idx = bo + nbnd * (zko + nlat(3) * (zjo + nlat(2) * zio))
c     
c     end subroutine packidx
c
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c
c-----The remaining keywords (with their meaning) in the standard input
c     file of EDF are the following (They are almost the same already 
c     described in the case IOVERLAP=-1.
c
c=====Record 3.i (i=1,NGROUP-1)  
c
c     nfugrp(i),(ifugrp(j,i),j=1,nfugrp(i)) [ minelec [  maxelec ] ]
c
c     Only groups from 1 to NGROUP-1 are defined below. The atoms in the 
c     last group are defined by difference. Atoms in the first NGROUP-1 
c     groups must necessarily belong to the set 1 <= atom <= NAOM; i.e.
c     ifugrp(j,i) .le. NAOM necessarily.
c
c     nfugrp(i)    = Number of atoms in group i.
c     ifugrp(j,i)  = Indices of atoms that belong to group i.
c     minelec      = Minimum number of ALPHA=BETA electrons in group i.
c     maxelec      = Maximum number of ALPHA=BETA electrons in group i.
c   
c     MINELEC and MAXELEC values are optional. If not given they are 
c     set to 0 and NMO, respectively. 
c
c=====Record 4: END
c
c     This indicates the end of the input of the present calculation.
c
c=====Record 5: LARGE
c
c     Large output is requested. The default is short output.
c
c=====Record 6: DNO
c
c     This order applies only when NGROUP=3. In this case, after reading
c     the AOM, this order performs the following tasks:
c     
c                                    1
c     1) Computes the matrix D_12 =  - [ S_1 S_2 + S_2 S_1 ]
c                                    2
c
c     where 1 and 2 labels the groups 1 and 2, respectively.
c
c     2) Diagonalizes D_12
c     3) Selects the eigenvalues of D_12 greater than epsbond (see below)
c     4) Construct the eigenvectors correponding to the above eigenvalues. 
c        These eigenvectors will be the DNOs (linear combinations of the 
c        original MOs), which are fully or partially localized in the joint 
c        fragment 1+2.
c     5) Reconstruct the AOM in terms of the DNOs.
c     6) Computes the EDF and the localization and delocalization 
c        indices
c
c
c=====Record 7: EPSBOND epsbond
c
c     epsbond is the parameter that controls the above order. The 
c     default value is 1D-7, and the minimum and maximum values that 
c     can be given in this order are 1D-10 and 1D-3, respectively.
c
c=====Record 8: FULLOC
c
c     Localizes the Molecular Orbitals using the defined groups (not the 
c     individual atoms) to contruct the localization function which is 
c     maximized, and computes the EDF of the molecule. A series of simpli-
c     fications to avoid numerical instabilities, very similar to the 
c     ones used in the order DNO above, are carried out before the EDF is 
c     actually obtained:
c
c     1) Performs the isopycnic localization.
c     2) Divides the isopycnic MOs in two sets: (a) MOs partially deloc-
c        alized in two or more fragments, and (b) MOs almost fully loca-
c        lized in an unique fragment. 
c     3) Excludes the set (b) from the computation of the EDF, adding
c        two electrons to the core of a fragment each time an isopycnic
c        MO is localized in this fragment.
c
c=====Record 9: EPSLOC epsloc
c
c     epsloc is the parameter that controls the FULLOC order. The 
c     default value is 1D-2, and the minimum and maximum values
c     1D-4 and 1D-2, respectively.
c
c=====Record 10: DAFH
c
c     Performs a DAFH analysis in each fragment and from the DAFH eigen-
c     values greater than epsdafh (see below) determines the maximum 
c     number of electrons in this fragment. 
c
c=====Record 11: EPSDAFH epsdafh
c
c     epsdafh is the parameter that controls the EPSDAFH order. If a
c     DAFH eigenvalue in a group satisfies value > epsdafh, the maximum
c     number of electrons of this group increased by 2.0.
c
c=====Record 12: PROBCUT pcut
c
c     In the output of probabilities, only those probabilities 
c     greater than pcut are written. The default is 1D-3
c
c     The records 6-12 can be given in any order.
c
c-----------------------------------------------------------------------
c
      USE          space_for_wfnbasis
      USE          space_for_wfncoef
      USE          space_for_cidet
      include     'implicit.inc'
      include     'wfn.inc'
      include     'stderr.inc'
      include     'constants.inc'
      include     'mline.inc'
      complex*16, allocatable,dimension (:,:,:)      :: sga,sgb
      real   (kind=8), allocatable,dimension (:,:)   :: kpt
      real   (kind=8), allocatable,dimension (:,:,:) :: occrit
      real   (kind=8), allocatable,dimension (:,:)   :: probr
      integer(kind=4), allocatable,dimension (:,:)   :: ifugrp
      integer(kind=4), allocatable,dimension (:,:)   :: cellatom
      integer(kind=4), allocatable,dimension (:,:)   :: eleca,elecb
      integer(kind=4), allocatable,dimension (:)     :: nfugrp,mocore
      integer(kind=4), allocatable,dimension (:,:)   :: resnca,resncb
      integer(kind=4), allocatable,dimension (:,:)   :: wnrimap
      real   (kind=8), allocatable,dimension (:)     :: diout
      complex*16,      allocatable,dimension (:,:)   :: aomtot
      real   (kind=8), allocatable,dimension (:,:,:,:)  :: deloc
      complex*16  aom1cmplx
      real(kind=8)      aom1
      integer     lw,lr
      logical     setint,ok,notingroup,goon,dno,largwr,localize,dodafh
      logical     setword
      character*(mline) line,word,uppcase
      real(kind=8)      epsbond,epsloc,epsdafh
c
      integer (kind = 4) :: nbnd,nmo,nlattot,nspin,nattr,sijtype
      integer (kind = 4) :: nbndw(1:2),nlat(1:3),idx(1:3)
      complex*16, allocatable,dimension (:,:,:,:)       :: sij
      character(len=8)   :: lblspin(2)
      
c
c-----------------------------------------------------------------------
c
      call timer (2,iedfcrit,'_edfcrit  ',-1)
      write (lw,57) 
c
c-----Start reading the binary file from critic2 with AOM integrals
c 
      read (lu18) nbnd,nbndw,nlat,nmo,nlattot,nspin,nattr,sijtype
c
c-----Only SIJTYPE=1 (i.e. the 'wannier' mode is allowed at this moment)
c
      if (sijtype.ne.1) then
        write (stderr,1) sijtype
        stop
      endif
      lblspin(1) = 'wannier '
      lblspin(2) = 'psink   '
      if (sijtype.eq.1 .or. sijtype.eq.2) then
        write (lw,300) nbnd,nbndw,nlat,nmo,nlattot,
     &    lblspin(sijtype),nspin,nattr
      endif
 300  format (' #',/,' # ',80('+'),/
     &   ' # Number of bands                            = ', I4,/,
     &   ' # Number of bands depending on the spin      = ',2I4,/,
     &   ' # Number of cells along x,y,z                = ',3I4,/,
     &   ' # Number of molecular orbitals               = ',I4,/,
     &   ' # Total number of cells                      = ',I4,/,
     &   ' # Sij AOM type                               = ',a8,/,
     &   ' # nspin                                      = ',I4,/,
     &   ' # Number of attractors in the reference cell = ',I4,/,
     &   ' # ',80('+'))
c
c-----The total number of unit cells must be equal to the product
c     of the number of unit cells along the x, y, z axes
c
      if (nlattot.ne.nlat(1)*nlat(2)*nlat(3)) then
        write (stderr,2) nlattot
        stop
      endif
c
c-----The number of molecular orbitals (nmo) must be equal to the product
c     of the number of bands (nbnd) and the number of cells (nlattot)
c
      if (nmo.ne.nlattot*nbnd) then
        write (stderr,3) nmo
        stop
      endif
      if (nspin.ne.1 .and. nspin.ne.2) then
        write (stderr,4) nspin
        stop
      endif
c
c-----kpt() and occrit() arrays are not used by now, but they must be
c     read in.
c
      allocate (kpt(3,nlattot))
      allocate (occrit(nbnd,nlattot,nspin))
      read (lu18) kpt
      read (lu18) occrit
      deallocate (kpt,occrit)
c
c-----Read the atomic overlap integrals (AOM) in the reference cell
c
      if (.not.allocated(sij)) then
        allocate (sij(nmo,nmo,nattr,nspin),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate sij()'
        read (lu18) sij
      endif
      close (lu18) 
c
c-----The wnrimap() array maps the R=0 AOM integrals to the R=R AOM integrals
c
      if (.not.allocated(wnrimap)) then
        allocate (wnrimap(nmo,nlattot),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate wnrimap()'
      endif
      if (.not.allocated(deloc)) then
        allocate (deloc(nattr,nattr,nlattot,nspin),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate deloc()'
      endif
      if (.not.allocated(diout)) then
        allocate (diout(nattr*nlattot),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate diout()'
      endif
      do imo = 1,nmo
c
c-------unpackidx returns the vector R=(Rx,Ry,Rz)=(ia,ja,ka) and the
c       band index 'n=iba' for the molecular orbital 'imo'
c
        call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
        k = 0
        do ic = 0, nlat(1)-1
          do jc = 0, nlat(2)-1
            do kc = 0, nlat(3)-1
              k = k + 1
              idx = (/ia-ic, ja-jc, ka-kc/)
              idx = modulo(idx,nlat)
              call packidx (idx(1),idx(2),idx(3),iba,map,nmo,nbnd,nlat)
              wnrimap(imo,k) = map
            end do
          end do
        end do
CcC     write (lw,70) imo,(wnrimap(imo,k),k=1,nlat(1)*nlat(2)*nlat(3))
      enddo
 70   format (' # WNRIMAP values for imo = ',I4,/,1000(1x,'#',20I4,/))
c
c-----ntotattr is the total number of attractors. We identify it with 
c     the number of attractors in the unit cell (nattr) multiplied by 
c     the total number of cells (nlattot)
c
      ntotattr = nattr * nlattot
c-----------------------------------------------------------------------
c
c-----Compute the sum of AOMs in all attractors of the system, testing
c     whether it is equal or not to the unit matrix.
c
      allocate (aomtot(nmo,nmo),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate aomtot()'
      aomtot = cmplx(0.0d+00,0.0d+00)
      do i = 1, nattr
        do k = 1, nlattot
          do imo = 1, nmo
            call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
            do jmo = 1, nmo
              call unpackidx (jmo,ib,jb,kb,ibb,nmo,nbnd,nlat)
              imomap = wnrimap(imo,k)
              jmomap = wnrimap(jmo,k)
              aomtot(imo,jmo) = aomtot(imo,jmo)+sij(imomap,jmomap,i,1)
            enddo
          enddo
        enddo
      enddo
CcC   write (lw,*) '# Sum AOMs in all attractors of the system to test'
CcC   write (lw,*) '# whether it is equal or not to the unit matrix'
      do i=1,nmo
        do j=1,nmo
CcC       write (lw,334) i,j,real(aomtot(i,j)),aimag(aomtot(i,j))
        enddo
      enddo
      deallocate (aomtot)
 334  format (1x,'# i,j = ',2I4,3x,'( ',F20.14,1x,F20.14,' )')
c
c-----------------------------------------------------------------------
c
c-----Compute localization and delocalization indices just for testing purposes
c
      do i = 1, nattr
        do j = 1, nattr
          do is = 1, nspin
            do k = 1, nlattot
              fatemp = 0.0d+00
              do imo = 1, nmo
                call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
                do jmo = 1, nmo
                  call unpackidx (jmo,ib,jb,kb,ibb,nmo,nbnd,nlat)
                  imomap = wnrimap(imo,k)
                  jmomap = wnrimap(jmo,k)
                  fatemp = fatemp + 
     &              real(sij(jmo,imo,i,is)*sij(imomap,jmomap,j,is),8)
                end do
              end do
              deloc(i,j,k,is) = fatemp
            end do
          end do
        end do
      end do
c
c-----Localization indices and electron populations
c
      fspin = 3.0d+00-dble(nspin)
      write (lw,20)
      do i = 1, nattr
        xli = sum(abs(deloc(i,i,1,:))) * fspin
        xnn = sum(abs(deloc(i,:,:,:))) * fspin
        write (lw,21) i,xli,xnn
      enddo
      write (lw,22)
      do i = 1,nattr
        xli = sum(abs(deloc(i,i,1,:))) * fspin
        xnn = sum(abs(deloc(i,:,:,:))) * fspin
        k = 0
        m = 0
        do ic = 0, nlat(1)-1
          do jc = 0, nlat(2)-1
            do kc = 0, nlat(3)-1
              k = k + 1
              do j = 1, nattr
                m = m + 1
                diout(m) = 2.0d+00 * sum(abs(deloc(i,j,k,:))) * fspin
                if (i == j .and. ic+jc+kc == 0) diout(m) = diout(m) / 2.0d+00
              enddo
            enddo
          enddo
        enddo
        write (lw,80) i
        do m = 1, nattr*nlattot
          write (lw,23) i,m,diout(m)
        enddo
        write (lw,24) i,xnn
      enddo
c
c-----ntotattr is the total number of attractors. We identify it with 
c     the number of attractors in the unit cell (nattr) multiplied by 
c     the total number of cells (nlattot)
c
c     ntotattr = nattr * nlattot
c
c-----Determine the maximum number of electrons of both spin-channels
c
      maxalpha = 0
      maxbeta  = 0
      if (nspin.eq.1) then
        maxalpha = nbnd * nlattot
        maxbeta  = nbnd * nlattot
      else
        do i=1,nbndw(1)
          do j=1,nlattot
            if (occrit(i,j,1).eq.1) maxalpha = maxalpha + 1
          enddo
        enddo
        do i=1,nbndw(2)
          do j=1,nlattot
            if (occrit(i,j,2).eq.1) maxbeta  = maxbeta  + 1
          enddo
        enddo
      endif
c
c-----Start reading the rest of the standard EDF input file.
c
      read (lr,'(a)') line
      lp = 1
      ok = setword(word,line,lp)
      word = uppcase(word)
      if (trim(word).ne.'NGROUP') then
        write (stderr,200)
        stop
      else
        if (setint(ngroup,line,lp)) then
          ngroup = abs(ngroup)
          if (ngroup.lt.2) write (stderr,201)
          if (ngroup.lt.2) stop
          if (ngroup.gt.5) write (stderr,202)
          if (ngroup.gt.5) stop
        else
          write (stderr,203)
          stop
        endif
      endif
      allocate (mocore(ngroup),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate mocore()'
      allocate (nfugrp(ngroup),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate nfugrp()'
      allocate (ifugrp(ntotattr,ngroup),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate ifugrp()'
      allocate (eleca(2,ngroup),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate eleca()'
      allocate (elecb(2,ngroup),stat=ier)
      if (ier.ne.0) stop '# edfcrit.f: Cannot allocate elecb()'
      do i=1,ngroup-1
        read (lr,'(a)') line
        lp = 1
        ok = setint(nfugrp(i),line,lp)
        if (.not.ok) then
           write (stderr,*) '# edfcrit.f: Error defining fragment',i
           stop
        endif
        do j=1,nfugrp(i)
          ok = setint(ifugrp(j,i),line,lp)
          if (.not.ok) then
            write (stderr,*) '# edfcrit.f: Error defining fragment',i
            stop
          endif
          if (ifugrp(j,i).lt.0) then
            stop '# edfcrit.f: Not valid read in atom'
          endif
        enddo

        eleca(1,i) = 0
        eleca(2,i) = maxalpha
        elecb(1,i) = 0
        elecb(2,i) = maxbeta

        if (setint(eleca(1,i),line,lp)) then
          if (eleca(1,i).lt.0) eleca(1,i) = 0
          if (eleca(1,i).gt.maxalpha) eleca(1,i) = maxalpha
          if (setint(eleca(2,i),line,lp)) then
            if (eleca(2,i).lt.0) eleca(2,i) = 0
            if (eleca(2,i).gt.maxalpha) eleca(2,i) = maxalpha
          endif
          if (eleca(1,i).gt.eleca(2,i)) then
            elecaux = eleca(1,i)
            eleca(1,i) = eleca(2,i)
            eleca(2,i) = elecaux
          elseif (eleca(1,i) == eleca(2,i)) then
            stop '# edfcrit.f: MinAlpha elec = MaxAlpha elec ???'
          endif
          if (nspin.eq.1) then
            elecb(1:2,i) = eleca(1:2,i)
            cycle
          endif
          if (setint(elecb(1,i),line,lp)) then
            if (elecb(1,i).lt.0) elecb(1,i) = 0
            if (elecb(1,i).gt.maxbeta) elecb(1,i) = maxbeta
            if (setint(elecb(2,i),line,lp)) then
              if (elecb(2,i).lt.0) elecb(2,i) = 0
              if (elecb(2,i).gt.maxbeta) elecb(2,i) = maxmaxbeta
            endif
            if (elecb(1,i).gt.elecb(2,i)) then
              elecaux = elecb(1,i)
              elecb(1,i) = elecb(2,i)
              elecb(2,i) = elecaux
            elseif (eleca(1,i) == eleca(2,i)) then
              stop '# edfcrit.f: MinBeta elec = MaxBeta elec ???'
            endif
          endif
        endif
      enddo
c
c.....Determine the atoms in the last group
c
      nfulast = 0
      do l=1,ntotattr
        notingroup = .true.
        do i=1,ngroup-1
          do j=1,nfugrp(i)
            if (l.eq.ifugrp(j,i)) notingroup=.false.
          enddo
        enddo
        if (notingroup) then
          nfulast = nfulast+1
          ifugrp(nfulast,ngroup) = l
        endif
      enddo
      nfugrp(ngroup) = nfulast
c
c.....Test that the group is not empty of atoms.
c
      do i=1,ngroup
        if (nfugrp(i).eq.0) then
          write (stderr,*) '# edfcrit.f:  GROUP ',i,' is empty'
          stop
        endif
      enddo
c
c.....Test that each atom belongs to a single group.
c
      do i=2,ngroup
        do k=1,i-1
          do m=1,nfugrp(k)
            do l=1,nfugrp(i)
              if (ifugrp(l,i).eq.ifugrp(m,k)) then
                 write (stderr,432) l,i,m,k
                 stop
              endif
            enddo
          enddo
        enddo
      enddo

      if (.not.allocated(cellatom)) then
        allocate (cellatom(ntotattr,4),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate cellatom()'
      endif
c
c-----Print info relative to the atoms composing the groups
c
      write (lw,50) 
 50   format (' # Information of atoms forming the groups')
 51   format (' # GROUP ',I4)
 52   format (' # Attractor =',I5,4x,'type_atom =',I5,4x,'cell = ',3I4)
      do i=1,ngroup
        write (lw,51) i
        do j=1,nfugrp(i)
          k = ifugrp(j,i)
          call unpackidx (k,io,jo,ko,itypo,ntotattr,nattr,nlat)
          cellatom(k,1) = io
          cellatom(k,2) = jo
          cellatom(k,3) = ko
          cellatom(k,4) = itypo
          write (lw,52) k,itypo,io,jo,ko
        enddo
      enddo
c
c-----Minimum and maximum number of electrons of the last group
c
      eleca(1,ngroup) = max(0,maxalpha - sum(eleca(2,1:ngroup-1)))
      eleca(2,ngroup) = maxalpha - sum(eleca(1,1:ngroup-1))
      elecb(1,ngroup) = max(0,maxbeta - sum(elecb(2,1:ngroup-1)))
      elecb(2,ngroup) = maxbeta - sum(elecb(1,1:ngroup-1))
c
      dno      = .false.
      localize = .false.
      dodafh   = .false.
      largwr   = .false.
      epsbond  = 1.0D-07
      epsloc   = 1.0D-02
      epsdafh  = 1.0D-03
c
c.....Read control parameters used in the calculation.
c
      pcut = 1.0D-03
      goon = .true.
      do while (goon) 
        read (lr,'(a)',end=110) line
        line = uppcase(line)
        lp = 1
        ok = setword(word,line,lp)
        if (word(1:1).eq.'#') then
        elseif (trim(word).eq.'END') then
          goon = .false.
        elseif (trim(word).eq.'DNO') then
          if (ngroup.eq.3) dno = .true.
        elseif (trim(word).eq.'LARGE' .or. trim(word).eq.'VERBOSE') then
          largwr = .true.
        elseif (trim(word).eq.'FULLOC') then
          localize = .true.
        elseif (trim(word).eq.'DAFH') then
          dodafh = .true.
        elseif (trim(word).eq.'EPSBOND') then
          line = line(lp:)
          read (line,*) epsbond
          epsbond = max(min(abs(epsbond),1.0D-03),1.0D-10)
        elseif (trim(word).eq.'EPSDAFH') then
          line = line(lp:)
          read (line,*) epsdafh
*         epsdafh = max(min(abs(epsdafh),1.0D-2),1.0D-6)
        elseif (trim(word).eq.'EPSLOC') then
          line = line(lp:)
          read (line,*) epsloc
          epsloc = max(min(abs(epsloc),1.0D-2),1.0D-4)
        elseif (trim(word).eq.'PROBCUT') then
          line = line(lp:)
          read (line,*) pcut
        else
          write (stderr,'(a)') ' # '//word(1:leng(word))
          write (stderr,*) '# Key word in input file not understood'
        endif
      enddo
 110  continue
c
c-----Determine AOM integrals for both spin channels
c-----Compute complex Group Overlap matrices of all but the last group.
c
      if (.not.allocated(sga)) then
        allocate (sga(ngroup,nmo,nmo),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate sga()'
      endif
      if (.not.allocated(sgb)) then
        allocate (sgb(ngroup,nmo,nmo),stat=ier)
        if (ier.ne.0) stop '# edfcrit.f: Cannot allocate sgb()'
      endif
c
      sga(:,:,:)=cmplx(0.0d+00,0.0d+00)
      sgb(:,:,:)=cmplx(0.0d+00,0.0d+00)
c
c-----Aqui
c
      do i=1,ngroup-1
        do j=1,nfugrp(i)
          k = ifugrp(j,i)
          io = cellatom(k,1)
          jo = cellatom(k,2)
          ko = cellatom(k,3)
          itypo = cellatom(k,4) 
          do imo=1,nmo
            call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
            idx = (/ia-io, ja-jo, ka-ko/)
            idx = modulo(idx,nlat)
            call packidx (idx(1),idx(2),idx(3),iba,mapi,nmo,nbnd,nlat)
            do jmo=1,nmo
              call unpackidx (jmo,ia,ja,ka,iba,nmo,nbnd,nlat)
              idx = (/ia-io, ja-jo, ka-ko/)
              idx = modulo(idx,nlat)
              call packidx (idx(1),idx(2),idx(3),iba,mapj,nmo,nbnd,nlat)
              sga(i,imo,jmo) = sga(i,imo,jmo) + sij(mapi,mapj,itypo,1)
            enddo
          enddo
        enddo
      enddo
      if (nspin.eq.1) then
        sgb(1:ngroup-1,:,:) = sga(1:ngroup-1,:,:)
      else
        do i=1,ngroup-1
         do j=1,nfugrp(i)
          k = ifugrp(j,i)
          io = cellatom(k,1)
          jo = cellatom(k,2)
          ko = cellatom(k,3)
          itypo = cellatom(k,4) 
          do imo=1,nmo
           call unpackidx (imo,ia,ja,ka,iba,nmo,nbnd,nlat)
           idx = (/ia-io, ja-jo, ka-ko/)
           idx = modulo(idx,nlat)
           call packidx (idx(1),idx(2),idx(3),iba,mapj,nmo,nbnd,nlat)
           do jmo=1,nmo
             call unpackidx (jmo,ia,ja,ka,iba,nmo,nbnd,nlat)
             idx = (/ia-io, ja-jo, ka-ko/)
             idx = modulo(idx,nlat)
             call packidx (idx(1),idx(2),idx(3),iba,mapj,nmo,nbnd,nlat)
             sgb(i,imo,jmo) = sgb(i,imo,jmo) + sij(mapi,mapj,itypo,2)
           enddo
          enddo
         enddo
        enddo
      endif
c
c-----Compute complex Group Overlap integrals of the last group.
c
      sga(ngroup,1:nmo,1:nmo) = cmplx(0.0d+00,0.0d+00)
      do m=1,nmo
        sga(ngroup,m,m) = cmplx(1.0d+00,0.0d+00)
      enddo
      do i=1,ngroup-1
        sga(ngroup,:,:) = sga(ngroup,:,:) - sga(i,:,:)
      enddo
      if (nspin.eq.1) then
        sgb(:,:,:) = sga(:,:,:)
      else
        sgb(ngroup,1:nmo,1:nmo) = cmplx(0.0d+00,0.0d+00)
        do m=1,nmo
          sgb(ngroup,m,m) = cmplx(1.0d+00,0.0d+00)
        enddo
        do i=1,ngroup-1
          sgb(ngroup,:,:) = sgb(ngroup,:,:) - sgb(i,:,:)
        enddo
      endif
c
      if (dno) then
        localize = .false.
        dodafh = .false.
      elseif (localize) then
        dodafh = .false.
        dno = .false.
      elseif (dodafh) then
        localize = .false.
        dno = .false.
      endif
c
c-----If there are only two groups neither DAFH, nor LOCALIZE, nor DNO
c     strategies are neccessary. Probabilities are obtaine in this case
c     by using the recursive formulas of Cançes, Savin, etc.
c
      if (ngroup.eq.2) then
        call twobascrit (sga,sgb,nmo,nspin,ngroup,pcut,lr,lw,stderr)
        call timer (4,iedfcrit,'_edfcrit  ',-1)
        return
      endif
c
      if (dno) then
        call dnocrit (sga,sgb,eleca,elecb,nmo,ntotattr,nattr,
     &   nspin,ngroup,nfugrp,ifugrp,pcut,epsbond,lr,lw,stderr)
         call timer (4,iedfcrit,'_edfcrit  ',-1)
         return
      endif
      
      if (dodafh) then
        call dafhcrit (sga,sgb,eleca,elecb,nmo,ntotattr,nattr,nspin,
     &    ngroup,nfugrp,ifugrp,pcut,epsdafh,lr,lw,stderr)
         call timer (4,iedfcrit,'_edfcrit  ',-1)
         return
      endif
c
c-----Write mininum and maximum population of the groups
c
      write (lw,82)
      do i=1,ngroup
        write (lw,81) i,eleca(1,i),eleca(2,i),elecb(1,i),elecb(2,i)
      enddo
      write (lw,83)
      npais = 1
      npbis = 1
      do i=1,ngroup-1
        npais = npais*(eleca(2,i)-eleca(1,i)+1)
        npbis = npbis*(elecb(2,i)-elecb(1,i)+1)
      enddo
      npreva = npais
      nprevb = npbis
c
      if (.not.allocated(resnca)) then
        allocate (resnca(npreva,ngroup),stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot allocate resnca()'
      endif
      if (.not.allocated(resncb)) then
        allocate (resncb(nprevb,ngroup),stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot allocate resncb()'
      endif
c
c.....Computation of ALPHA and BETA resonance structures.
c
      call rnprobs (eleca,resnca,nmo,ngroup,npais,lw)
      if (npreva.lt.npais) then
        write (stderr,*) 'edfcrit.f: rnprobs.f returns NPREVA < NPAIS'
        stop
      endif
      call rnprobs (elecb,resncb,nmo,ngroup,npbis,lw)
      if (nprevb.lt.npbis) then
        write (stderr,*) 'edfcrit.f: rnprobs.f returns NPREVB < NPBIS'
        stop
      endif
c
c.....Compute EDF using an isopycnic localized orbitals
c
cAqui
      localize = .false.
      if (localize) then
        call critlocmplx (sga,sgb,nmo,ngroup,ntotattr,nattr,nspin,
     &      nfugrp,ifugrp,pcut,lw,epsloc,.true.)
         call timer (4,iedfcrit,'_edfcrit  ',-1)
         return
      endif
c
c.....Compute EDF without using the DNO or ISOPYCNIC modules.
c
      write (lw,766) nmo,ntotattr,nattr,ngroup
      do i=1,ngroup
*       write (lw,764) i,eleca(1,i),eleca(2,i),elecb(1,i),elecb(2,i)
        write (lw,767) i,nfugrp(i)
        write (lw,765) (ifugrp(j,i),j=1,nfugrp(i))
      enddo
      mocore(1:ngroup)=0
*     call critcplx (pcut,npais,npbis,ngroup,nmo,nmo,lw,
*    &     eleca,elecb,sga,sgb,resnca,resncb,mocore)
      call xcritcplx (pcut,npais,npbis,ngroup,nmo,nmo,lw,
     &     eleca,elecb,sga,sgb,resnca,resncb,mocore)

      if (allocated(nfugrp)) then
        deallocate (nfugrp,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate nfugrp()'
      endif
      if (allocated(ifugrp)) then
        deallocate (ifugrp,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate ifugrp()'
      endif
      if (allocated(sga)) then
        deallocate (sga,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate sga()'
      endif
      if (allocated(sgb)) then
        deallocate (sgb,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate sgb()'
      endif
      if (allocated(eleca)) then
        deallocate (eleca,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate eleca()'
      endif
      if (allocated(elecb)) then
        deallocate (elecb,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate elecb()'
      endif
      if (allocated(resnca)) then
        deallocate (resnca,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate resnca()'
      endif
      if (allocated(resncb)) then
        deallocate (resncb,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate resncb()'
      endif
      if (allocated(mocore)) then
        deallocate (mocore,stat=ier)
        if (ier.ne.0) stop 'edfcrit.f: Cannot deallocate mocore()'
      endif
      call timer (4,iedfcrit,'_edfcrit  ',-1)
      return
 766  format (
     & ' # Number of Complex Molecular Orbitals       = ',I4,/,
     & ' # Total number of attractors                 = ',I4,/,
     & ' # Number of attractors in the reference cell = ',I4,/,
     & ' # Number of groups that divide the system    = ',I4)
 764  format (' # GROUP ',I2,
     &  ' MinElec and MaxElec (alpha) = ',2I6,/,
     &  ' MinElec and MaxElec (beta ) = ',2I6)
 767  format (1x,'# Number of atoms in group ',I4,' = ',I4)
 765  format (1000(' # ',20I5,/))
 432  format (1x,'#',/,1x,'# Atom number ',I3,' of group ',I2,
     & 1x,'is equal to atom number ',I3,' of group ',I2,/,1x,'#')
 57   format (1x,'# CRITIC2 Atomic Overlap Matrix is read in')
 1    format (' # The variable sijtype is ',I2,'. However ...',/,
     & ' # only sijtype = 1 (i.e. "wannier" mode) is allowed for now')
 2    format (' # The variable nlattot is ',I2,'. However, it must',/,
     & ' # be equal to "nlat(1)*nlat(2)*nlat(3)"')
 3    format (' The variable nmo is ',I4,'. However, it must',/,
     & ' # be equal to "nlattot*nbnd"')
 4    format (' The variable nspin is ',I4,'. However, it must',/,
     & ' # be equal to 1 or 2')
 20   format (' # ',80('+'),/,
     & ' # Localization indices and electron populations',/,
     & ' # ',80('+'))
 21   format (' # Attractor ',I2,4x,'LI = ',F12.8,4x,'N = ',F12.8)
 22   format (
     & ' # ',80('+'),/,' # Delocalization indices.',
     & ' Each block corresponds to a single atom in the main cell',/,
     & ' # A = B ---> LI(A). A /= B ---> DI(AB)',/,
     & ' # Last line: LI(A) + 0.5 * SUM_{B /= A} DI(AB) = Electron ',
     & ' population',/,' # ',80('+'))
 23   format (' # DI ( ',I2,I4,' ) = ',F12.8)
 24   format (' # N  ( ',I2,' )     = ',F12.8)
 80   format (' # Attractor ',I2)
 200  format (' # Order "NGROUP ngroup" not read from the input file')
 201  format (' # The minimum allowed value for ngroup is 2')
 202  format (' # The maximum allowed value for ngroup is 5')
 203  format (' # Value of "ngroup" not read in from the input file')
 82   format (' #',/,' # ',76('+'),/,
     &   ' # Minimum and Maximum population of groups',/,' # ',76('+'))
 81   format (' # Group ',I2,5x,'(MinElec,MaxElec), Alpha --> ',2I5,4x,
     &                                             'Beta  --> ',2I5)
 83   format (' # ',76('+'))
      end
c
c-----------------------------------------------------------------------
c
c-----Unpacking routine for use in delocalization index calculations.
c
      subroutine unpackidx(idx,io,jo,ko,bo,nmo,nbnd,nlat)
        integer, intent(in) :: idx, nmo, nbnd, nlat(3)
        integer, intent(out) :: io, jo, ko, bo
      
        integer :: iaux
      
        iaux = modulo(idx-1,nmo)
        bo = modulo(iaux,nbnd)
        iaux = (idx-1 - bo) / nbnd
        ko = modulo(iaux,nlat(3))
        iaux = (iaux - ko) / nlat(3)
        jo = modulo(iaux,nlat(2))
        iaux = (iaux - jo) / nlat(2)
        io = modulo(iaux,nlat(1))
        bo = bo + 1
      
      end subroutine unpackidx
c
c-----------------------------------------------------------------------
c
c-----Packing routine for use in delocalization index calculations.
c
      subroutine packidx(io,jo,ko,bo,idx,nmo,nbnd,nlat)
        integer, intent(in) :: io, jo, ko, bo, nmo, nbnd, nlat(3)
        integer, intent(out) :: idx
      
        integer :: zio, zjo, zko
      
        zio = modulo(io,nlat(1))
        zjo = modulo(jo,nlat(2))
        zko = modulo(ko,nlat(3))
      
        idx = bo + nbnd * (zko + nlat(3) * (zjo + nlat(2) * zio))

      end subroutine packidx
